spring.application.name=twinSpring
spring.web.resources.add-mappings=true

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3306/digital_twin}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Abcd1234}

spring.h2.console.enabled=false

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

mybatis.mapper-locations=classpath:/mapper/*.xml
mybatis.type-aliases-package=yyj.project.twinspring.dto

bim.server.url=${BIM_SERVER_URL:http://localhost:5112}
mqtt.broker.url=${MQTT_BROKER_URL:tcp://localhost:1883}
mqtt.topic=${MQTT_TOPIC:test/topic}

logging.level.yyj.project.twinspring=INFO
spring.sql.init.mode=always